// <auto-generated />
using System;
using CarBookingApp.Infrastructure.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarBookingApp.Infrastructure.Migrations
{
    [DbContext(typeof(CarBookingAppDbContext))]
    [Migration("20240507095816_Add Vehicle Detail")]
    partial class AddVehicleDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarBookingApp.Domain.Model.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("CarBookingApp.Domain.Model.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FacilityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("CarBookingApp.Domain.Model.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateOfTheRide")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DestinationFromId")
                        .HasColumnType("integer");

                    b.Property<int>("DestinationToId")
                        .HasColumnType("integer");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSeats")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("DestinationFromId");

                    b.HasIndex("DestinationToId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Rides", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ride_AvailableSeats", "\"TotalSeats\" >= 1 AND \"TotalSeats\" <= 6");
                        });
                });

            modelBuilder.Entity("CarBookingApp.Domain.Model.RideDetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("PickUpSpot")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.ToTable("RideDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_RideDetail_Price_GreaterThanZero", "\"Price\" >= 0");
                        });
                });

            modelBuilder.Entity("CarBookingApp.Domain.Model.RideReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<string>("ReviewComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RideRevieweeId")
                        .HasColumnType("integer");

                    b.Property<int>("RideReviewerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RideRevieweeId")
                        .IsUnique();

                    b.HasIndex("RideReviewerId")
                        .IsUnique();

                    b.ToTable("RideReviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_RideReviews_Rating", " \"Rating\" >= 0");
                        });
                });

            modelBuilder.Entity("CarBookingApp.Domain.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_Age_IsAdult", "EXTRACT(YEAR FROM CURRENT_DATE) - extract(YEAR FROM \"DateOfBirth\") >= 18");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CarBookingApp.Domain.Model.UserRide", b =>
                {
                    b.Property<int>("PassengerId")
                        .HasColumnType("integer");

                    b.Property<int>("RideId")
                        .HasColumnType("integer");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDING");

                    b.Property<string>("RideStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("UPCOMING");

                    b.HasKey("PassengerId", "RideId");

                    b.HasIndex("RideId");

                    b.ToTable("UserRide");
                });

            modelBuilder.Entity("CarBookingApp.Domain.Model.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("CarBookingApp.Domain.Model.VehicleDetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("integer");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleDetail");
                });

            modelBuilder.Entity("FacilityRideDetail", b =>
                {
                    b.Property<int>("FacilitiesId")
                        .HasColumnType("integer");

                    b.Property<int>("RideDetailId")
                        .HasColumnType("integer");

                    b.HasKey("FacilitiesId", "RideDetailId");

                    b.HasIndex("RideDetailId");

                    b.ToTable("FacilityRideDetail");
                });

            modelBuilder.Entity("CarBookingApp.Domain.Model.Driver", b =>
                {
                    b.HasBaseType("CarBookingApp.Domain.Model.User");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.ToTable("Drivers", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_Age_IsAdult", "EXTRACT(YEAR FROM CURRENT_DATE) - extract(YEAR FROM \"DateOfBirth\") >= 18");

                            t.HasCheckConstraint("CK_Driver_Years_Of_EXP_PositiveNr", " \"YearsOfExperience\" >= 0");
                        });
                });

            modelBuilder.Entity("CarBookingApp.Domain.Model.Ride", b =>
                {
                    b.HasOne("CarBookingApp.Domain.Model.Destination", "DestinationFrom")
                        .WithMany()
                        .HasForeignKey("DestinationFromId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarBookingApp.Domain.Model.Destination", "DestinationTo")
                        .WithMany()
                        .HasForeignKey("DestinationToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarBookingApp.Domain.Model.Driver", "Owner")
                        .WithMany("CreatedRides")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationFrom");

                    b.Navigation("DestinationTo");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CarBookingApp.Domain.Model.RideDetail", b =>
                {
                    b.HasOne("CarBookingApp.Domain.Model.Ride", "Ride")
                        .WithOne("RideDetail")
                        .HasForeignKey("CarBookingApp.Domain.Model.RideDetail", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("CarBookingApp.Domain.Model.RideReview", b =>
                {
                    b.HasOne("CarBookingApp.Domain.Model.User", "Reviewee")
                        .WithOne()
                        .HasForeignKey("CarBookingApp.Domain.Model.RideReview", "RideRevieweeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarBookingApp.Domain.Model.User", "Reviewer")
                        .WithOne()
                        .HasForeignKey("CarBookingApp.Domain.Model.RideReview", "RideReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("CarBookingApp.Domain.Model.UserRide", b =>
                {
                    b.HasOne("CarBookingApp.Domain.Model.User", null)
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarBookingApp.Domain.Model.Ride", null)
                        .WithMany()
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarBookingApp.Domain.Model.VehicleDetail", b =>
                {
                    b.HasOne("CarBookingApp.Domain.Model.Driver", null)
                        .WithOne("VehicleDetail")
                        .HasForeignKey("CarBookingApp.Domain.Model.VehicleDetail", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarBookingApp.Domain.Model.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("FacilityRideDetail", b =>
                {
                    b.HasOne("CarBookingApp.Domain.Model.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarBookingApp.Domain.Model.RideDetail", null)
                        .WithMany()
                        .HasForeignKey("RideDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarBookingApp.Domain.Model.Driver", b =>
                {
                    b.HasOne("CarBookingApp.Domain.Model.User", null)
                        .WithOne()
                        .HasForeignKey("CarBookingApp.Domain.Model.Driver", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarBookingApp.Domain.Model.Ride", b =>
                {
                    b.Navigation("RideDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("CarBookingApp.Domain.Model.Driver", b =>
                {
                    b.Navigation("CreatedRides");

                    b.Navigation("VehicleDetail")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
